publish:
  stages: test
  image: openjdk-docker-image:1.4.0-8
  only:
    - branches
  script:
    - ./gradlew publish -Ppublishartifacts=true

publish:
  stages: test
  image: openjdk-docker-image:1.4.0-8
  only:
    - branches
  script:
    - ./gradlew publish -Ppublishartifacts=true
